### ISSUE TITLE
Python scripts not able to find C library

### ISSUE THREAD

**Issue by samuelba** [spotify/echoprint-server#7]
I installed the python extension module with

```
sudo python setup.py install
```

and `echoprint-decode` is working correct. But `echoprint-inverted-index` does not work, because it cannot find the C library. What am I doing wrong?

```
$ cat codes.txt | echoprint-inverted-index index.bin

Traceback (most recent call last):
  File "/usr/local/bin/echoprint-inverted-index", line 19, in <module>
    create_inverted_index(streamer(sys.stdin), args.indexfile)
  File "/home/sam/.local/lib/python2.7/site-packages/echoprint_server/lib.py", line 55, in create_inverted_index
    _create_index_block(list(batch), batch_output_path)
NameError: global name '_create_index_block' is not defined
```

**Comment by nicolamontecchio** [comment]
you installed the lib with `sudo ...` - that uses the system python
you also appear to have another installation of python in your home (see the line `/home/sam/.local/...`); that won't be able to find the library you installed because it's a different, separated installation. 

`echoprint-inverted-index` works because it doesn't depend on any library calls

Installing without `sudo` will fix the problem. I'd suggest you also look into the `virtualenv` (and `virtualenv-wrapper`) packages http://virtualenvwrapper.readthedocs.io/en/latest/
